//! Auto-generated `LIBRARY.md` bootstrap file at the library root.

use std::fs;
use std::path::PathBuf;

use chrono::Utc;
use serde::Serialize;

use crate::catalog::{catalog, Catalog};
use crate::error::Result;
use crate::index::Index;
use crate::store::Library;
use crate::threads::{list_threads, ThreadsResult};

pub const LIBRARY_OVERVIEW_FILENAME: &str = "LIBRARY.md";

#[derive(Debug, Clone, Serialize)]
pub struct LibraryOverviewReport {
    pub path: String,
    pub written: bool,
}

/// Regenerate `LIBRARY.md` at the library root. Only writes when content changes.
pub fn regenerate_library_overview(
    library: &Library,
    index: &Index,
) -> Result<LibraryOverviewReport> {
    let cat = catalog(index)?;
    let threads = list_threads(library, index, None)?;
    let body = render_library_overview_body(library, &cat, &threads);
    let path = library.root.join(LIBRARY_OVERVIEW_FILENAME);

    let written = if path.exists() {
        let existing = fs::read_to_string(&path)?;
        if normalize_overview(&existing) == body.trim() {
            false
        } else {
            fs::write(&path, wrap_library_overview(&body))?;
            true
        }
    } else {
        fs::write(&path, wrap_library_overview(&body))?;
        true
    };

    Ok(LibraryOverviewReport {
        path: path.display().to_string(),
        written,
    })
}

fn normalize_overview(content: &str) -> String {
    content
        .lines()
        .filter(|line| {
            !line.starts_with("<!-- Generated by alexandria")
                && !line.starts_with("- **Generated:**")
        })
        .collect::<Vec<_>>()
        .join("\n")
        .trim()
        .to_string()
}

fn wrap_library_overview(body: &str) -> String {
    format!(
        "<!-- Generated by alexandria consolidate. Do not edit by hand. -->\n\n{body}\n- **Generated:** {}\n",
        Utc::now().to_rfc3339()
    )
}

fn render_library_overview_body(
    library: &Library,
    cat: &Catalog,
    threads: &ThreadsResult,
) -> String {
    let collections_section = if cat.collections.is_empty() {
        "_No collections yet._".to_string()
    } else {
        cat.collections
            .iter()
            .map(|c| {
                let summary = collection_summary_line(library, &c.name);
                format!("- **{}** ({}) — {}", c.name, c.count, summary)
            })
            .collect::<Vec<_>>()
            .join("\n")
    };

    let tags_section = if cat.tags.is_empty() {
        "_No tags yet._".to_string()
    } else {
        cat.tags
            .iter()
            .map(|t| format!("- `{}` ({})", t.name, t.count))
            .collect::<Vec<_>>()
            .join("\n")
    };

    let threads_section = if threads.threads.is_empty() {
        "_No open threads._".to_string()
    } else {
        threads
            .threads
            .iter()
            .take(20)
            .map(|t| format!("- [{}] {}", t.id, t.claim))
            .collect::<Vec<_>>()
            .join("\n")
    };

    format!(
        r#"# Library Overview

> Zero-tool-call orientation for agents arriving at this Alexandria library.
> For live counts and facets, run `alexandria catalog`. For retrieval, use `alexandria recall`.

- **Library root:** `{root}`
- **Total engrams:** {total}

## Collections

{collections_section}

## Tags

{tags_section}

## Open threads

{threads_section}

## Conventions

- **Plain text is truth:** engrams live as Markdown + YAML frontmatter; `.alexandria/index.db` is rebuildable.
- **Atomic unit:** one engram = one claim with provenance — not a synthesized concept article.
- **Tiers:** working (ephemeral), episodic, provisional, semantic, procedural, relational (generation-only, never quoted).
- **Typed edges:** use explicit relations (`supports`, `conflicts_confirmed`, `depends_on`, etc.), not wiki links.
- **Honest recall:** `recall` returns five states (`strong_hit`, `weak_hit`, `high_confidence_gap`, `low_confidence_gap`, `nothing`).
- **Curated export:** share a memory slice with `alexandria pack export --collection <name> --target <path>`.
"#,
        root = library
            .root
            .canonicalize()
            .unwrap_or_else(|_| library.root.clone())
            .display(),
        total = cat.total_engrams,
        collections_section = collections_section,
        tags_section = tags_section,
        threads_section = threads_section,
    )
}

fn collection_summary_line(library: &Library, name: &str) -> String {
    let slug = name.replace('/', "-");
    let path: PathBuf = library.root.join("collections").join(format!("{slug}.md"));
    if !path.exists() {
        return "no rollup yet".into();
    }
    let content = fs::read_to_string(path).unwrap_or_default();
    for line in content.lines() {
        let trimmed = line.trim();
        if trimmed.starts_with("Collection `") {
            return trimmed.to_string();
        }
    }
    "rollup available".into()
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::engram::{Engram, Status, Tier};
    use crate::provider::build_embedder;
    use tempfile::TempDir;

    #[test]
    fn library_overview_is_idempotent() {
        let dir = TempDir::new().unwrap();
        let lib = Library::init(dir.path()).unwrap();
        let mut config = crate::Config::load(dir.path()).unwrap();
        config.providers.embedder = "hash".into();
        let embedder = build_embedder(&config).unwrap();
        let index = Index::open_with_embedder(&lib, embedder).unwrap();

        let engram = Engram::new("test claim", "body", Tier::Semantic, Status::Confirmed);
        let p = lib.write_engram(&engram).unwrap();
        index.upsert(&engram, &p.display().to_string()).unwrap();

        let first = regenerate_library_overview(&lib, &index).unwrap();
        assert!(first.written);
        assert!(dir.path().join(LIBRARY_OVERVIEW_FILENAME).exists());

        let second = regenerate_library_overview(&lib, &index).unwrap();
        assert!(!second.written);
    }
}
